import { describe, expect, test } from 'vite-plus/test';
import {
  generateHandlerTypes,
  generateTsconfig,
  generateVirtualRoutesModule,
  toHandlerTypesPath,
} from '../src/codegen.js';

describe('generateVirtualRoutesModule', () => {
  test('generates imports and route definitions', () => {
    const module = generateVirtualRoutesModule([
      { filePath: '/my-app/worker/routes/api/index.ts', pattern: '/api' },
      { filePath: '/my-app/worker/routes/api.test.[id]/index.ts', pattern: '/api/test/[id]' },
    ]);

    expect(module).toMatchInlineSnapshot(`
      "import * as module$0 from "/my-app/worker/routes/api/index.ts";
      import * as module$1 from "/my-app/worker/routes/api.test.[id]/index.ts";

      export const routes = [
        {
          pattern: "/api",
          segments: [
            { kind: "static", value: "api" },
          ],
          module: module$0,
        },
        {
          pattern: "/api/test/[id]",
          segments: [
            { kind: "static", value: "api" },
            { kind: "static", value: "test" },
            { kind: "param", name: "id" },
          ],
          module: module$1,
        },
      ];
      "
    `);
  });
});

describe('generateHandlerTypes', () => {
  test('generates handler type for params', () => {
    expect(generateHandlerTypes('/api/test/[params]')).toMatchInlineSnapshot(`
      "// Generated by vite-plugin-cloudflare-router. Do not edit.

      import type { DefineHandler, DefineMiddleware } from 'vite-plugin-cloudflare-router/runtime';

      export const defineHandler: DefineHandler<{ params: string }>;
      export const defineMiddleware: DefineMiddleware<{ params: string }>;
      export { json } from 'vite-plugin-cloudflare-router/runtime';
      "
    `);
  });

  test('generates handler type for catch-all', () => {
    expect(generateHandlerTypes('/api/test/[...catchall]')).toMatchInlineSnapshot(`
      "// Generated by vite-plugin-cloudflare-router. Do not edit.

      import type { DefineHandler, DefineMiddleware } from 'vite-plugin-cloudflare-router/runtime';

      export const defineHandler: DefineHandler<{ catchall: string[] }>;
      export const defineMiddleware: DefineMiddleware<{ catchall: string[] }>;
      export { json } from 'vite-plugin-cloudflare-router/runtime';
      "
    `);
  });
});

describe('generateTsconfig', () => {
  test('generates tsconfig', () => {
    expect(generateTsconfig()).toMatchInlineSnapshot(`
      "{
        "files": [
          "virtual.d.ts"
        ],
        "compilerOptions": {
          "rootDirs": [
            "..",
            "./types"
          ]
        }
      }
      "
    `);
  });
});

describe('toHandlerTypesPath', () => {
  test('mirrors source directory as +types/index.d.ts', () => {
    const rootDir = '/my-app';
    const routeDir = '/my-app/src/routes/api.test.[params]';
    const path = toHandlerTypesPath(rootDir, routeDir);

    expect(path).toBe(
      '/my-app/.cloudflare-router/types/src/routes/api.test.[params]/+types/index.d.ts',
    );
  });
});
