import { describe, expect, test } from 'vite-plus/test';
import {
  generateHandlerTypes,
  generateTsconfig,
  generateVirtualModule,
  generateVirtualModuleAmbient,
  toHandlerTypesPath,
} from '../src/codegen.js';

describe('generateVirtualModule', () => {
  test('generates imports and route definitions', () => {
    const module = generateVirtualModule([
      { filePath: '/my-app/worker/routes/api/index.ts', pattern: '/api' },
      { filePath: '/my-app/worker/routes/api.test.[id]/index.ts', pattern: '/api/test/[id]' },
    ]);

    expect(module).toMatchInlineSnapshot(`
      "import * as module$0 from "/my-app/worker/routes/api/index.ts";
      import * as module$1 from "/my-app/worker/routes/api.test.[id]/index.ts";

      export const routes = [
        {
          pattern: "/api",
          segments: [
            { kind: "static", value: "api" },
          ],
          module: module$0,
        },
        {
          pattern: "/api/test/[id]",
          segments: [
            { kind: "static", value: "api" },
            { kind: "static", value: "test" },
            { kind: "param", name: "id" },
          ],
          module: module$1,
        },
      ];
      "
    `);
  });
});

describe('generateVirtualModuleAmbient', () => {
  test('generates ambient module declaration', () => {
    expect(generateVirtualModuleAmbient()).toMatchInlineSnapshot(`
      "// Generated by vite-plugin-cloudflare-router. Do not edit.

      declare module 'virtual:cloudflare-router' {
        import type { RouteDefinition } from 'vite-plugin-cloudflare-router/runtime';
        export const routes: RouteDefinition[];
      }
      "
    `);
  });
});

describe('generateHandlerTypes', () => {
  test('generates handler type for params', () => {
    expect(generateHandlerTypes('/api/test/[params]')).toMatchInlineSnapshot(`
      "// Generated by vite-plugin-cloudflare-router. Do not edit.

      import { defineHandler as $defineHandler, defineMiddleware as $defineMiddleware, type DefineHandler, type DefineMiddleware } from 'vite-plugin-cloudflare-router/runtime';

      export { json } from 'vite-plugin-cloudflare-router/runtime';
      export const defineHandler = $defineHandler as DefineHandler<{ params: string }>;
      export const defineMiddleware = $defineMiddleware as unknown as DefineMiddleware<{ params: string }>;
      "
    `);
  });

  test('generates handler type for catch-all', () => {
    expect(generateHandlerTypes('/api/test/[...catchall]')).toMatchInlineSnapshot(`
      "// Generated by vite-plugin-cloudflare-router. Do not edit.

      import { defineHandler as $defineHandler, defineMiddleware as $defineMiddleware, type DefineHandler, type DefineMiddleware } from 'vite-plugin-cloudflare-router/runtime';

      export { json } from 'vite-plugin-cloudflare-router/runtime';
      export const defineHandler = $defineHandler as DefineHandler<{ catchall: string[] }>;
      export const defineMiddleware = $defineMiddleware as unknown as DefineMiddleware<{ catchall: string[] }>;
      "
    `);
  });
});

describe('generateTsconfig', () => {
  test('generates tsconfig', () => {
    expect(generateTsconfig()).toMatchInlineSnapshot(`
      "{
        "files": [
          "virtual.d.ts"
        ],
        "compilerOptions": {
          "rootDirs": [
            "..",
            "./types"
          ]
        }
      }
      "
    `);
  });
});

describe('toHandlerTypesPath', () => {
  test('mirrors route file path', () => {
    const rootDir = '/my-app';
    const routeFile = '/my-app/src/routes/api.test.[params]/index.ts';
    const path = toHandlerTypesPath(rootDir, routeFile);

    expect(path).toBe(
      '/my-app/.cloudflare-router/types/src/routes/api.test.[params]/+types/index.ts',
    );
  });
});
