import type { Routes } from './index.js';
import type { Segment } from './runtime.js';
import fs from 'node:fs';
import path from 'node:path';
import { normalizePath } from 'vite';
import { patternToSegments } from './index.js';

export const TYPES_ROOT_DIR = '.cloudflare-router';
export const HANDLER_TYPES_DIR = '+types';

/**
 * Generates virtual module source.
 * Generated `routes` is consumed by `createRouter` to handle routes.
 *
 * @param {Routes[]} routes - A list of routes to generate a virtual module for.
 * @returns {string} The virtual module source.
 *
 * @example
 * ```ts
 * import { routes } from 'virtual:cloudflare-router';
 * import { createRouter } from 'vite-plugin-cloudflare-router/runtime';
 *
 * const router = createRouter(routes);
 * ```
 */
export function generateVirtualModule(routes: Routes[]) {
  const imports = routes.map(
    (route, i) => `import * as module$${i} from ${JSON.stringify(normalizePath(route.filePath))};`,
  );
  const definitions = routes.map((route, i) =>
    [
      '  {',
      `    pattern: ${JSON.stringify(route.pattern)},`,
      `    segments: ${segmentsToLiteral(patternToSegments(route.pattern))},`,
      `    module: module$${i},`,
      '  },',
    ].join('\n'),
  );

  // oxfmt-ignore
  return [
    ...imports,
    '',
    'export const routes = [',
    ...definitions,
    '];',
    '',
  ].join('\n');
}

/**
 * Generates ambient module declaration for virtual module (`virtual:cloudflare-router`).
 * Declaration file is created in `.cloudflare-router/virtual.d.ts`, which makes
 * `import { routes } from 'virtual:cloudflare-router';` be recognized.
 *
 * @returns {string} The `.d.ts` source.
 *
 * @example
 * ```ts
 * import { routes } from 'virtual:cloudflare-router';
 * import { createRouter } from 'vite-plugin-cloudflare-router/runtime';
 *
 * const router = createRouter(routes);
 * ```
 */
export function generateVirtualModuleAmbient() {
  return [
    '// Generated by vite-plugin-cloudflare-router. Do not edit.',
    '',
    "declare module 'virtual:cloudflare-router' {",
    "  import type { RouteDefinition } from 'vite-plugin-cloudflare-router/runtime';",
    '  export const routes: RouteDefinition[];',
    '}',
    '',
  ].join('\n');
}

/**
 * Types for route handler module that re-exports a `defineHandler` for
 * each route, so `params` is inferred from the route's pattern.
 *
 * @param {string} pattern - The route's pattern.
 * @returns {string} The types for the route handler module.
 *
 * @example
 * ```ts
 * // e.g. /api/hello/[name].ts
 * import { defineHandler, json } from './+types/[name]';
 *
 * export const GET = defineHandler().handle(({ params }) => {
 *   return json({ message: `Hello ${params.name}!` });
 * });
 * ```
 */
export function generateHandlerTypes(pattern: string) {
  const paramsType = paramsTypeFromPattern(pattern);
  return [
    '// Generated by vite-plugin-cloudflare-router. Do not edit.',
    '',
    "import { defineHandler as $defineHandler, defineMiddleware as $defineMiddleware, type DefineHandler, type DefineMiddleware } from 'vite-plugin-cloudflare-router/runtime';",
    '',
    "export { json } from 'vite-plugin-cloudflare-router/runtime';",
    `export const defineHandler = $defineHandler as DefineHandler<${paramsType}>;`,
    `export const defineMiddleware = $defineMiddleware as unknown as DefineMiddleware<${paramsType}>;`,
    '',
  ].join('\n');
}

/**
 * Generates `.cloudflare-router/tsconfig.json`.
 * Apps `extends` this file, so `virtual.d.ts` and handler types are loaded.
 * `rootDirs` makes `./+types` resolve into `./types` from a route file.
 *
 * @returns {string} The `tsconfig.json` source.
 *
 * @example
 * ```json
 * {
 *   "extends": "./.cloudflare-router/tsconfig.json",
 *   "compilerOptions": {
 *     // ...
 *   },
 *   "include": ["src"]
 * }
 * ```
 */
export function generateTsconfig() {
  const tsconfig = {
    files: ['virtual.d.ts'],
    compilerOptions: {
      rootDirs: ['..', './types'],
    },
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

/**
 * Writes `.cloudflare-router` that `tsconfig.json` extends, which contains
 * `tsconfig.json`, `virtual.d.ts`, and handler types.
 * Mirroring the source tree so it resolves as `./+types`.
 *
 * @param {string} rootDir - The root directory of the project.
 * @param {Routes[]} routes - Scanned routes, used to generate handler types.
 *
 * @example
 * ```
 * .cloudflare-router/
 * ├── types/src/routes/example.[id]/+types/index.ts
 * ├── tsconfig.json
 * └── virtual.d.ts
 * ```
 */
export function writeGeneratedTypes(rootDir: string, routes: Routes[]) {
  const outDir = path.join(rootDir, TYPES_ROOT_DIR);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, '.gitignore'), '*');
  fs.writeFileSync(path.join(outDir, 'tsconfig.json'), generateTsconfig());
  fs.writeFileSync(path.join(outDir, 'virtual.d.ts'), generateVirtualModuleAmbient());
  writeHandlerTypes(rootDir, routes);
}

function writeHandlerTypes(rootDir: string, routes: Routes[]) {
  const typesDir = path.join(rootDir, TYPES_ROOT_DIR, 'types');
  fs.rmSync(typesDir, { recursive: true, force: true });

  for (const route of routes) {
    const outFile = toHandlerTypesPath(rootDir, route.filePath);
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, generateHandlerTypes(route.pattern));
  }
}

/**
 * Converts a route file's path to the path of its generated handler types.
 * Mirroring the source tree so it resolves as `./+types`.
 *
 * @param {string} rootDir - The root directory of the project.
 * @param {string} routeFile - Path to the route file.
 * @returns {string} Path to the generated `+types` module.
 *
 * @example
 * ```ts
 * toHandlerTypesPath('/app', '/app/src/routes/example.[id]/index.ts');
 * // '/app/.cloudflare-router/types/src/routes/example.[id]/+types/index.ts'
 * ```
 */
export function toHandlerTypesPath(rootDir: string, routeFile: string) {
  const relativeDir = path.dirname(path.relative(rootDir, routeFile));
  return path.join(
    rootDir,
    TYPES_ROOT_DIR,
    'types',
    relativeDir,
    HANDLER_TYPES_DIR,
    path.basename(routeFile),
  );
}

function paramsTypeFromPattern(pattern: string) {
  const paramsType: string[] = [];
  for (const segment of patternToSegments(pattern)) {
    if (segment.kind === 'param') {
      paramsType.push(`${segment.name}: string`);
    }
    if (segment.kind === 'catchall') {
      paramsType.push(`${segment.name}: string[]`);
    }
  }
  if (paramsType.length === 0) {
    return '{}';
  }
  return `{ ${paramsType.join('; ')} }`;
}

function segmentsToLiteral(segments: Segment[]) {
  if (segments.length === 0) {
    return '[]';
  }
  const lines = segments.map((segment) => `      ${segmentToLiteral(segment)},`);
  return ['[', ...lines, '    ]'].join('\n');
}

function segmentToLiteral(segment: Segment) {
  if (segment.kind === 'static') {
    return `{ kind: "static", value: ${JSON.stringify(segment.value)} }`;
  }
  return `{ kind: "${segment.kind}", name: ${JSON.stringify(segment.name)} }`;
}
