import type { Routes } from './index.js';
import type { Segment } from './runtime.js';
import fs from 'node:fs';
import path from 'node:path';
import { normalizePath } from 'vite';
import { patternToSegments } from './index.js';

export const TYPES_ROOT_DIR = '.cloudflare-router';
export const HANDLER_TYPES_DIR = '+types';

/**
 * Generates virtual module source.
 * Generated `routes` is consumed by `createRouter` to handle routes.
 *
 * @param {Routes[]} routes - A list of routes to generate a virtual module for.
 * @returns {string} The virtual module source.
 *
 * @example
 * ```ts
 * import { routes } from 'virtual:cloudflare-router';
 * import { createRouter } from 'vite-plugin-cloudflare-router/runtime';
 *
 * const router = createRouter(routes);
 * ```
 */
export function generateVirtualRoutesModule(routes: Routes[]) {
  const imports = routes.map(
    (route, i) => `import * as module$${i} from ${JSON.stringify(normalizePath(route.filePath))};`,
  );
  const definitions = routes.map((route, i) =>
    [
      '  {',
      `    pattern: ${JSON.stringify(route.pattern)},`,
      `    segments: ${segmentsToLiteral(patternToSegments(route.pattern))},`,
      `    module: module$${i},`,
      '  },',
    ].join('\n'),
  );

  // oxfmt-ignore
  return [
    ...imports,
    '',
    'export const routes = [',
    ...definitions,
    '];',
    '',
  ].join('\n');
}

/**
 * Generates ambient module declaration for virtual module (`virtual:cloudflare-router`).
 * Declaration file is created in `.cloudflare-router/virtual.d.ts`, which makes
 * `import { routes } from 'virtual:cloudflare-router';` be recognized.
 *
 * @returns {string} The `.d.ts` source.
 *
 * @example
 * ```ts
 * import { routes } from 'virtual:cloudflare-router';
 * import { createRouter } from 'vite-plugin-cloudflare-router/runtime';
 *
 * const router = createRouter(routes);
 * ```
 */
function generateVirtualModuleAmbient() {
  return [
    '// Generated by vite-plugin-cloudflare-router. Do not edit.',
    '',
    "declare module 'virtual:cloudflare-router' {",
    "  import type { RouteDefinition } from 'vite-plugin-cloudflare-router/runtime';",
    '  export const routes: RouteDefinition[];',
    '}',
    '',
  ].join('\n');
}

/**
 * Runtime module loaded for `./+types` import.
 */
export function generateHandlerRuntime() {
  return "export { defineHandler, defineMiddleware, json } from 'vite-plugin-cloudflare-router/runtime';";
}

/**
 * Types for route handler module, so `params` is inferred from the route's pattern.
 *
 * @param {string} pattern - The route's pattern.
 * @returns {string} The types for the route handler module.
 *
 * @example
 * ```ts
 * // e.g. src/routes/api.hello.[name]/index.ts
 * import { defineHandler, json } from './+types';
 *
 * export const GET = defineHandler().handle(({ params }) => {
 *   return json({ message: `Hello ${params.name}!` });
 * });
 * ```
 */
export function generateHandlerTypes(pattern: string) {
  const paramsType = paramsTypeFromPattern(pattern);
  return [
    '// Generated by vite-plugin-cloudflare-router. Do not edit.',
    '',
    "import type { DefineHandler, DefineMiddleware } from 'vite-plugin-cloudflare-router/runtime';",
    '',
    `export const defineHandler: DefineHandler<${paramsType}>;`,
    `export const defineMiddleware: DefineMiddleware<${paramsType}>;`,
    "export { json } from 'vite-plugin-cloudflare-router/runtime';",
    '',
  ].join('\n');
}

/**
 * Generates `.cloudflare-router/tsconfig.json`.
 * Apps `extends` this file, so `virtual.d.ts` and handler types are loaded.
 * `rootDirs` makes `./+types` resolve into `./types` from a route file.
 *
 * @returns {string} The `tsconfig.json` source.
 *
 * @example
 * ```json
 * {
 *   "extends": "./.cloudflare-router/tsconfig.json",
 *   "compilerOptions": {
 *     // ...
 *   },
 *   "include": ["src"]
 * }
 * ```
 */
export function generateTsconfig() {
  const tsconfig = {
    files: ['virtual.d.ts'],
    compilerOptions: {
      rootDirs: ['..', './types'],
    },
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

/**
 * Writes `.cloudflare-router` that `tsconfig.json` extends, which contains
 * `tsconfig.json`, `virtual.d.ts`, and handler types.
 * Mirroring the source tree so it resolves as `./+types`.
 *
 * @param {string} rootDir - The root directory of the project.
 * @param {Routes[]} routes - Scanned routes, used to generate handler types.
 *
 * @example
 * ```
 * .cloudflare-router/
 * ├── types/src/routes/example.[id]/+types/index.d.ts
 * ├── tsconfig.json
 * └── virtual.d.ts
 * ```
 */
export function writeGeneratedTypes(rootDir: string, routes: Routes[]) {
  const outDir = path.join(rootDir, TYPES_ROOT_DIR);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, '.gitignore'), '*');
  fs.writeFileSync(path.join(outDir, 'tsconfig.json'), generateTsconfig());
  fs.writeFileSync(path.join(outDir, 'virtual.d.ts'), generateVirtualModuleAmbient());
  writeHandlerTypes(rootDir, routes);
}

function writeHandlerTypes(rootDir: string, routes: Routes[]) {
  const typesDir = path.join(rootDir, TYPES_ROOT_DIR, 'types');
  fs.rmSync(typesDir, { recursive: true, force: true });

  for (const route of routes) {
    const source = generateHandlerTypes(route.pattern);
    const routeDir = path.dirname(route.filePath);
    writeHandlerType(rootDir, routeDir, source);
    // `/` lives in the routes directory, which is also the parent of every
    // other route. Walking it would write `/` types into sibling directories.
    if (route.pattern === '/') {
      continue;
    }
    for (const nestedDir of nestedDirs(routeDir)) {
      writeHandlerType(rootDir, nestedDir, source);
    }
  }
}

function writeHandlerType(rootDir: string, routeDir: string, source: string) {
  const outFile = toHandlerTypesPath(rootDir, routeDir);
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, source);
}

function nestedDirs(routeDir: string) {
  const SOURCE_FILE_RE = /\.(?:[m]?ts|[m]?js)$/;
  const dirs = new Set<string>();

  function walk(dir: string) {
    if (!fs.existsSync(dir)) {
      return;
    }
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }
      if (entry.isFile() && SOURCE_FILE_RE.test(entry.name)) {
        dirs.add(dir);
      }
    }
  }

  if (!fs.existsSync(routeDir)) {
    return [];
  }

  for (const entry of fs.readdirSync(routeDir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      walk(path.join(routeDir, entry.name));
    }
  }

  return [...dirs];
}

/**
 * Converts a route directory to the path of its generated handler types.
 * Mirroring the source tree so it resolves as `./+types`.
 *
 * @param {string} rootDir - The root directory of the project.
 * @param {string} routeDir - Directory of the route or colocated module.
 * @returns {string} Path to the generated `+types` module.
 *
 * @example
 * ```ts
 * toHandlerTypesPath('/app', '/app/src/routes/example.[id]');
 * // '/app/.cloudflare-router/types/src/routes/example.[id]/+types/index.d.ts'
 * ```
 */
export function toHandlerTypesPath(rootDir: string, routeDir: string) {
  const relativeDir = path.relative(rootDir, routeDir);
  return path.join(rootDir, TYPES_ROOT_DIR, 'types', relativeDir, HANDLER_TYPES_DIR, 'index.d.ts');
}

function paramsTypeFromPattern(pattern: string) {
  const paramsType: string[] = [];
  for (const segment of patternToSegments(pattern)) {
    if (segment.kind === 'param') {
      paramsType.push(`${segment.name}: string`);
    }
    if (segment.kind === 'catchall') {
      paramsType.push(`${segment.name}: string[]`);
    }
  }
  if (paramsType.length === 0) {
    return '{}';
  }
  return `{ ${paramsType.join('; ')} }`;
}

function segmentsToLiteral(segments: Segment[]) {
  if (segments.length === 0) {
    return '[]';
  }
  const lines = segments.map((segment) => `      ${segmentToLiteral(segment)},`);
  return ['[', ...lines, '    ]'].join('\n');
}

function segmentToLiteral(segment: Segment) {
  if (segment.kind === 'static') {
    return `{ kind: "static", value: ${JSON.stringify(segment.value)} }`;
  }
  return `{ kind: "${segment.kind}", name: ${JSON.stringify(segment.name)} }`;
}
