const HTTP_METHODS = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'HEAD', 'OPTIONS', 'QUERY'] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

interface Bindings {
  ASSETS: {
    fetch: (request: Request) => Promise<Response>;
  };
}

export interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

type Params = Record<string, string | string[]>;

interface RouteContext<Env = unknown, P extends Params = Params, Input = unknown> {
  request: TypedRequest<Input>;
  env: Env;
  ctx: ExecutionContext;
  params: P;
}

type RouteHandler<Env = unknown, P extends Params = Params> = (
  context: RouteContext<Env, P>,
) => Response | Promise<Response>;

type FallbackHandler<Env = unknown> = (
  request: Request,
  env: Env,
  ctx: ExecutionContext,
) => Response | Promise<Response>;

type RouteModule = {
  [M in HttpMethod]?: RouteHandler<never>;
} & {
  ALL?: RouteHandler<never>;
};

export type Segment =
  | { kind: 'static'; value: string }
  | { kind: 'param'; name: string }
  | { kind: 'catchall'; name: string };

export interface RouteDefinition {
  pattern: string;
  segments: Segment[];
  module: RouteModule;
}

interface RouteMatch {
  module: RouteModule;
  params: Params;
}

interface RouterConfig<Env = unknown> {
  /**
   * Called when no route matches. Defaults to `env.ASSETS.fetch(request)` when
   * an ASSETS binding exists, otherwise a 404 Not Found response.
   *
   * @example
   * ```ts
   * const router = createRouter(routes, {
   *   fallback: (request, env, ctx) => {
   *     return new Response('Not Found', { status: 404 });
   *   },
   * });
   * ```
   */
  fallback?: FallbackHandler<Env>;
}

interface Router<Env = unknown> {
  /**
   * Handles a route request.
   *
   * @param {Request} request - The incoming request.
   * @param {Env} env - Cloudflare's environment bindings.
   * @param {ExecutionContext} ctx - Cloudflare's execution context.
   * @returns {Promise<Response>} The response to the incoming request.
   *
   * @example
   * ```ts
   * const router = createRouter<Env>(routes);
   *
   * export default {
   *   fetch: (request, env, ctx) => router.handle(request, env, ctx),
   * } satisfies ExportedHandler<Env>;
   * ```
   */
  handle(request: Request, env: Env, ctx: ExecutionContext): Promise<Response>;
}

/**
 * Creates a router from route definitions generated by virtual module
 * (`virtual:cloudflare-router`). Route definitions are pre-parsed and sorted, so
 * this function only wires them up to handle requests.
 *
 * @param {RouteDefinition[]} routes - A list of route definitions to create a router from.
 * @param {RouterConfig<Env>} config - A configuration object for the router.
 * @returns {Router<Env>} A router that handles requests.
 *
 * @example
 * ```ts
 * import { routes } from 'virtual:cloudflare-router';
 * import { createRouter } from 'vite-plugin-cloudflare-router/runtime';
 *
 * const router = createRouter<Env>(routes);
 * ```
 */
export function createRouter<Env = unknown>(
  routes: RouteDefinition[],
  config: RouterConfig<Env> = {},
): Router<Env> {
  async function handle(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);
    const matched = match(routes, url.pathname);

    if (!matched) {
      const fallback = config.fallback ?? defaultFallback;
      return fallback(request, env, ctx);
    }

    const { module, params } = matched;
    const method = request.method.toUpperCase() as HttpMethod;
    const handler = module[method] ?? (method === 'HEAD' ? module.GET : undefined) ?? module.ALL;

    if (!handler) {
      const allow = new Set(HTTP_METHODS.filter((m) => module[m]));
      if (allow.has('GET')) {
        allow.add('HEAD');
      }
      if (module.ALL) {
        HTTP_METHODS.forEach((m) => allow.add(m));
      }
      return new Response('Method Not Allowed', {
        status: 405,
        headers: { Allow: [...allow].join(', ') },
      });
    }

    return (handler as RouteHandler<Env>)({ request, env, ctx, params });
  }

  return { handle };
}

function match(routes: RouteDefinition[], pathname: string): RouteMatch | undefined {
  const pathSegments = pathname.split('/').filter(Boolean);

  for (const route of routes) {
    const matched = matchRoute(route, pathSegments);
    if (matched) {
      return matched;
    }
  }
}

function matchRoute(route: RouteDefinition, pathSegments: string[]): RouteMatch | undefined {
  const { segments, module } = route;
  const last = segments[segments.length - 1];
  const hasCatchall = last && last.kind === 'catchall';

  if (hasCatchall && pathSegments.length < segments.length) {
    return;
  }
  if (!hasCatchall && pathSegments.length !== segments.length) {
    return;
  }

  const params: Params = {};

  for (const [i, segment] of segments.entries()) {
    if (segment.kind === 'catchall') {
      params[segment.name] = pathSegments.slice(i).map(decodeSegment);
      return { module, params };
    }

    const pathSegment = pathSegments[i];
    if (pathSegment === undefined) {
      return;
    }
    const value = decodeSegment(pathSegment);

    if (segment.kind === 'static' && segment.value !== value) {
      return;
    }
    if (segment.kind === 'param') {
      params[segment.name] = value;
    }
  }

  return { module, params };
}

const defaultFallback: FallbackHandler = (request, env) => {
  if (hasAssetsBinding(env)) {
    return env.ASSETS.fetch(request);
  }
  return new Response('Not Found', { status: 404 });
};

function hasAssetsBinding(env: unknown): env is Bindings {
  return isObject(env) && isObject(env.ASSETS) && typeof env.ASSETS.fetch === 'function';
}

function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function decodeSegment(segment: string) {
  try {
    return decodeURIComponent(segment);
  } catch {
    return segment;
  }
}

interface TypedRequest<Input = unknown> extends Request {
  json(): Promise<Input>;
}

interface TypedResponse<T = unknown> extends Response {
  json(): Promise<T>;
}

/**
 * Like `Response.json`, but keeps the payload type.
 *
 * @param {T} data - The data to send in the response.
 * @param {ResponseInit} init - The Response object's options.
 * @returns {TypedResponse<T>} A response with the JSON body.
 *
 * @example
 * ```ts
 * export const GET = () => {
 *   return json({ message: 'Hello, world!' });
 * };
 * ```
 */
export function json<T>(data: T, init?: ResponseInit): TypedResponse<T> {
  return Response.json(data, init) as TypedResponse<T>;
}
