const HTTP_METHODS = ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS', 'QUERY'] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

declare global {
  namespace Cloudflare {
    interface Env {}
  }
}

interface Bindings {
  ASSETS: {
    fetch: (request: Request) => Promise<Response>;
  };
}

export interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

type Params = Record<string, string | string[]>;

export interface RouteContext<E = Cloudflare.Env, P = Params> {
  request: Request;
  env: E;
  ctx: ExecutionContext;
  params: P;
}

export type RouteHandler<E = Cloudflare.Env, P = Params> = (
  context: RouteContext<E, P>,
) => Response | Promise<Response>;

type FallbackHandler<E = Cloudflare.Env> = (
  request: Request,
  env: E,
  ctx: ExecutionContext,
) => Response | Promise<Response>;

type RouteModule = {
  [M in HttpMethod]?: RouteHandler;
} & {
  ALL?: RouteHandler;
};

export type Segment =
  | { kind: 'static'; value: string }
  | { kind: 'param'; name: string }
  | { kind: 'catchall'; name: string };

export interface RouteDefinition {
  pattern: string;
  segments: Segment[];
  module: RouteModule;
}

interface Route {
  module: RouteModule;
  params: Params;
}

interface RouterConfig<E = Cloudflare.Env> {
  /**
   * Called when no route matches. Defaults to `env.ASSETS.fetch(request)` when
   * an ASSETS binding exists, otherwise a 404 Not Found response.
   *
   * @example
   * ```ts
   * const router = createRouter(routes, {
   *   fallback: (request, env, ctx) => {
   *     return new Response('Not Found', { status: 404 });
   *   },
   * });
   * ```
   */
  fallback?: FallbackHandler<E>;
}

interface Router<E = Cloudflare.Env> {
  /**
   * Handles a route request.
   *
   * @param {Request} request - The incoming request.
   * @param {E} env - Cloudflare's environment bindings.
   * @param {ExecutionContext} ctx - Cloudflare's execution context.
   * @returns {Promise<Response>} The response to the incoming request.
   *
   * @example
   * ```ts
   * const router = createRouter(routes);
   *
   * export default {
   *   fetch: (request, env, ctx) => router.handle(request, env, ctx),
   * } satisfies ExportedHandler<Env>;
   * ```
   */
  handle(request: Request, env: E, ctx: ExecutionContext): Promise<Response>;
}

/**
 * Creates a router from route definitions generated by virtual module
 * (`virtual:cloudflare-router`). Route definitions are pre-parsed and sorted, so
 * this function only wires them up to handle requests.
 *
 * @param {RouteDefinition[]} routes - A list of route definitions to create a router from.
 * @param {RouterConfig<E>} config - A configuration object for the router.
 * @returns {Router<E>} A router that handles requests.
 *
 * @example
 * ```ts
 * import { routes } from 'virtual:cloudflare-router';
 * import { createRouter } from 'vite-plugin-cloudflare-router/runtime';
 *
 * const router = createRouter(routes);
 * ```
 */
export function createRouter<E extends Cloudflare.Env = Cloudflare.Env>(
  routes: RouteDefinition[],
  config: RouterConfig<E> = {},
): Router<E> {
  async function handle(request: Request, env: E, ctx: ExecutionContext) {
    const url = new URL(request.url);
    const route = match(routes, url.pathname);

    if (!route) {
      const fallback = config.fallback ?? defaultFallback;
      return fallback(request, env, ctx);
    }

    return dispatch(request.method, route, request, env, ctx);
  }

  async function dispatch(
    method: string,
    route: Route,
    request: Request,
    env: E,
    ctx: ExecutionContext,
  ): Promise<Response> {
    if (method === 'HEAD') {
      const response = await dispatch('GET', route, request, env, ctx);
      return new Response(null, response);
    }
    const { module, params } = route;
    const handler = resolveHandler(method, module);
    return handler({ request, env, ctx, params });
  }

  return { handle };
}

declare const EXT: unique symbol;

/**
 * Response returned by `next()` inside a middleware. Carries the extended context which
 * makes `defineHandler().use()` and `defineHandler().handle()` able to access.
 */
export type NextResponse<Ext extends object = {}> = Response & { readonly [EXT]?: Ext };

/**
 * Runs the rest of the chain; another middleware if any and then handler.
 */
export type Next = <Ext extends object = {}>(ext?: Ext) => Promise<NextResponse<Ext>>;

/**
 * A middleware built by `defineMiddleware` which is then used by `defineHandler().use()`.
 * Either returns a `Response` to early return, or calls `next()` to continue the chain.
 */
export type Middleware<C = RouteContext, Ext extends object = {}> = (
  context: C,
  next: Next,
) => Response | NextResponse<Ext> | Promise<Response | NextResponse<Ext>>;

/**
 * Builder returned by `defineHandler`.
 *
 * @template {Params} P
 * @template {RouteContext} C
 *
 * @example
 * ```ts
 * import { defineHandler, defineMiddleware, json } from './+types';
 *
 * const requestId = defineMiddleware().handle((c, next) => {
 *   return next({ requestId: crypto.randomUUID() });
 * });
 *
 * export const GET = defineHandler()
 *   .use(requestId)
 *   .handle(({ requestId }) => {
 *     return json({ message: `requestId: ${requestId}` });
 *   });
 * ```
 */
export interface HandlerBuilder<C = RouteContext, P = Params> {
  use<Ext extends object = {}>(middleware: Middleware<C, Ext>): HandlerBuilder<C & Ext, P>;
  handle<H extends (context: C) => Response | Promise<Response>>(handler: H): H;
}

/**
 * Starts a route handler builder.
 *
 * @returns {HandlerBuilder} A builder for the route handler.
 *
 * @example
 * ```ts
 * import { defineHandler, json } from './+types';
 *
 * export const GET = defineHandler().handle(({ params }) => {
 *   return json({ message: `Hello ${params.name}!` });
 * });
 * ```
 */
export function defineHandler(): HandlerBuilder {
  return handlerBuilder([]);
}

function handlerBuilder(middlewares: Middleware<any, any>[]): HandlerBuilder<any, any> {
  return {
    use: (middleware: Middleware<any, any>) => handlerBuilder([...middlewares, middleware]),
    handle: (handler) => {
      if (middlewares.length === 0) {
        return handler;
      }
      const handle = (context: any) => dispatchMiddlewares(middlewares, context, handler);
      return handle as typeof handler;
    },
  };
}

async function dispatchMiddlewares(
  middlewares: Middleware<any, any>[],
  context: any,
  handler: (context: any) => Response | Promise<Response>,
) {
  let called = -1;

  async function dispatch(index: number, context: any) {
    if (index <= called) {
      throw new Error('next() called multiple times');
    }

    called = index;
    const middleware = middlewares[index];

    if (!middleware) {
      return handler(context);
    }

    const next: Next = (ext) => dispatch(index + 1, ext ? { ...context, ...ext } : context);
    const result = await middleware(context, next);

    if (!(result instanceof Response)) {
      throw new Error('Middleware must call next() or return a Response');
    }

    return result;
  }

  return dispatch(0, context);
}

/**
 * Builder returned by `defineMiddleware`.
 *
 * @template {Params} P
 * @template {RouteContext<Cloudflare.Env, P>} C
 *
 * @example
 * ```ts
 * import { defineMiddleware, json } from './+types';
 *
 * export const requestId = defineMiddleware().handle((c, next) => {
 *   return next({ requestId: crypto.randomUUID() });
 * });
 * ```
 */
export interface MiddlewareBuilder<P = Params, C = RouteContext<Cloudflare.Env, P>> {
  handle<Ext extends object = {}>(
    middleware: (
      context: C,
      next: Next,
    ) => Response | NextResponse<Ext> | Promise<Response | NextResponse<Ext>>,
  ): Middleware<C, Ext>;
}

/**
 * Starts a middleware builder. The built middleware is passed to
 * `defineHandler().use()`.
 *
 * @returns {MiddlewareBuilder} A builder for the middleware.
 *
 * @example
 * ```ts
 * import { defineHandler, defineMiddleware, json } from './+types';
 *
 * const requestId = defineMiddleware().handle((c, next) => {
 *   return next({ requestId: crypto.randomUUID() });
 * });
 *
 * export const GET = defineHandler()
 *   .use(requestId)
 *   .handle(({ requestId }) => json({ requestId }));
 * ```
 */
export function defineMiddleware(): MiddlewareBuilder {
  return {
    handle: (middleware) => middleware,
  };
}

/**
 * Call signature of `defineHandler` for each route.
 * Generated `./+types` casts `defineHandler` so `params` are inferred.
 *
 * @template {Params} P
 *
 * @example
 * ```ts
 * export const defineHandler = $defineHandler as DefineHandler<{ id: string }>;
 * ```
 */
export interface DefineHandler<P = Params> {
  (): HandlerBuilder<RouteContext<Cloudflare.Env, P>, P>;
}

/**
 * Call signature of `defineMiddleware` for each route.
 * Generated `./+types` casts `defineMiddleware` so `params` are inferred.
 *
 * @template {Params} P
 *
 * @example
 * ```ts
 * export const defineMiddleware = $defineMiddleware as DefineMiddleware<{ id: string }>;
 * ```
 */
export interface DefineMiddleware<P = Params> {
  (): MiddlewareBuilder<P>;
}

function match(routes: RouteDefinition[], pathname: string): Route | undefined {
  const pathSegments = pathname.split('/').filter(Boolean);

  for (const route of routes) {
    const matched = matchRoute(route, pathSegments);
    if (matched) {
      return matched;
    }
  }
}

function matchRoute(route: RouteDefinition, pathSegments: string[]): Route | undefined {
  const { segments, module } = route;
  const last = segments[segments.length - 1];
  const hasCatchall = last && last.kind === 'catchall';

  if (hasCatchall && pathSegments.length < segments.length) {
    return;
  }
  if (!hasCatchall && pathSegments.length !== segments.length) {
    return;
  }

  const params: Params = {};

  for (const [i, segment] of segments.entries()) {
    if (segment.kind === 'catchall') {
      params[segment.name] = pathSegments.slice(i).map(decodeSegment);
      return { module, params };
    }

    const pathSegment = pathSegments[i];
    if (pathSegment === undefined) {
      return;
    }
    const value = decodeSegment(pathSegment);

    if (segment.kind === 'static' && segment.value !== value) {
      return;
    }
    if (segment.kind === 'param') {
      params[segment.name] = value;
    }
  }

  return { module, params };
}

const defaultFallback: FallbackHandler<unknown> = (request, env) => {
  if (hasAssetsBinding(env)) {
    return env.ASSETS.fetch(request);
  }
  return new Response('Not Found', { status: 404 });
};

function resolveHandler(httpMethod: string, module: RouteModule) {
  const handler = isHttpMethod(httpMethod) ? module[httpMethod] : undefined;
  return handler ?? module.ALL ?? methodNotAllowedHandler(module);
}

function methodNotAllowedHandler(module: RouteModule) {
  const allowedMethods: Uppercase<string>[] = HTTP_METHODS.filter((m) => module[m]);
  if (module.GET) {
    allowedMethods.push('HEAD');
  }
  return () =>
    new Response('Method Not Allowed', {
      status: 405,
      headers: { Allow: allowedMethods.join(', ') },
    });
}

function isHttpMethod(httpMethod: string): httpMethod is HttpMethod {
  return HTTP_METHODS.some((m) => m === httpMethod);
}

function hasAssetsBinding(env: unknown): env is Bindings {
  return isObject(env) && isObject(env.ASSETS) && typeof env.ASSETS.fetch === 'function';
}

function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function decodeSegment(segment: string) {
  try {
    return decodeURIComponent(segment);
  } catch {
    return segment;
  }
}

interface TypedResponse<T = unknown> extends Response {
  json(): Promise<T>;
}

/**
 * Like `Response.json`, but keeps the payload type.
 *
 * @param {T} data - The data to send in the response.
 * @param {ResponseInit} init - The Response object's options.
 * @returns {TypedResponse<T>} A response with the JSON body.
 *
 * @example
 * ```ts
 * export const GET = () => {
 *   return json({ message: 'Hello, world!' });
 * };
 * ```
 */
export function json<T>(data: T, init?: ResponseInit): TypedResponse<T> {
  return Response.json(data, init) as TypedResponse<T>;
}
